language: go

sudo: true

go:
  - tip

install:
  - sudo apt-get install -y swig
  - go get -u ./...
  - go get -u github.com/stretchr/testify/assert

script:
  - go test -v -bench=. -benchmem -cover ./...
